config/routes.rb
Rails.application.routes.draw do
  
  resources :orders do 
    resources :comments do 
      get 'like', to: 'likes#create'
      delete 'dislike', to: 'likes#destroy'
      # delete '/orders/:order_id/comments/:comment_id/likes/:id' => 'likes#destroy'
      # resources :likes, only: %i[new create destroy]
    end
  end
  devise_for :users
  root 'home#index'
  get 'my_order', to: 'orders#my_orders'
  get 'search_order', to: 'orders#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord

belongs_to :user
has_many :comments, as: :commentable , dependent: :destroy   
def self.search(param)
    param.strip!
    to_send_back = (order_number_matches(param) + title_matches(param) + description_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end
  
  def self.order_number_matches(param)
    matches('order_number', param)
  end
  
  def self.title_matches(param)
    matches('title', param)
  end
  
  def self.description_matches(param)
    matches('description', param)
  end
  
  def self.matches(field_name, param)   #self so that convert it to class method not write User
    where("#{field_name} like ?", "%#{param}%")
  end
# ------------------------------------------


# def get_last_ten_records
#   Order.limit(10).order('id desc').reverse
# end

# ---------------------------------------------
  
  def self.to_csv
    # attr_reader :order_nmber, :title, :description
    attributes = %w{order_number title description recieved recieved_by approved approved_by closed closed_by remarks status actions issued_by}
   
    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |order|
        csv << attributes.map{ |attr| order.send(attr) }
      end
    end
  end
  
  # def self.to_csv
  #   attr_accessor :order_nmber, :title, :description
  #   CSV.generate do |csv|
  #     csv << column_names
  #     all.each do |product|
  #       csv << product.attributes.values_at(*column_names)
  #     end
  #   end
  # end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only:[:edit, :update, :destroy]
  
  def my_orders 
    @pendding_orders = get_pendding_orders
    respond_to do |format|
      format.html
      format.csv { send_data current_user.orders.to_csv, filename: "orders-#{Date.today}.csv" }
    end
  end


  def search 
    if params[:order].present?
      @orders_search_res = Order.search(params[:order])
      if @orders_search_res
          respond_to do |format|
            format.js {render partial: 'orders/search_result'}
          end
      else
          respond_to do |format|
            flash.now[:alert] = "Couldn`t find work order"
            format.js {render partial: 'orders/search_result'}
          end
      end
    else
          respond_to do |format|
              flash.now[:alert] = "Please enter order, name , email to search"
              format.js {render partial: 'orders/search_result'}
          end
    end
  end

  # GET /orders or /orders.json
  def index
    @orders = Order.all.order(:order_number)
    respond_to do |format|
      format.html
      format.csv { send_data @orders.to_csv, filename: "orders-#{Date.today}.csv" }
    end
  end

  # GET /orders/1 or /orders/1.json
  def show
    @comment = Comment.new
    @comments = Comment.where(commentable_type: :Order, commentable_id: @order.id).order(:created_at)
  end

  # GET /orders/new
  def new
    @order = Order.new
    @order_id = get_order_id
  end

  # GET /orders/1/edit
  def edit
      @order_id = @order.order_number
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)
    @order.user = current_user
    respond_to do |format|
      if @order.save
        format.html { redirect_to order_url(@order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:order_number, :title, :description, :recieved, :recieved_by, :approved, :approved_by, :closed, :closed_by, :remarks, :status, :actions, :issued_by)
    end

    def get_pendding_orders
      orders = Order.all 
      orders_arr = []
        orders.each do |order|
          if order.status == "Pendding Approvals"
          orders_arr << order 
          end
        end
        return orders_arr  
    end 
    
    def get_order_id
      order = Order.where(id: 1)
    
      if order.exists?
        order_id = Order.last.id + 1
      else
        order_id = 1
      end
      year_day = Date.today.yday
      year = Date.today.year
      "WO-#{year_day}-#{order_id}-#{year}"
    end

    def require_same_user
      if current_user != @order.user 
        flash[:alert] = "you can only edit or delete your own order"
        redirect_to @order 
      end

    end
  end

app/helpers/orders_helper.rb
module OrdersHelper
    
end

app/views/orders/_comments.html.erb
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<section class="content-item" id="comments">
    <div class="container">   
    	<div class="row">
            <div class="col-sm-8">
                <%= form_with model: [@order, @comment] do |form| %>
                    <% if @comment.errors.any? %>
                            <div id="error_explanation">
                                <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this order from being saved:</h2>
                                <ul>
                                <% @comment.errors.each do |error| %>
                                    <li><%= error.full_message %></li>
                                <% end %>
                                </ul>
                            </div>
                        <% end %> 
                        
                	<h3 class="pull-left">New Comment for order: <%= @order.order_number %></h3> 
                        <div class="form-group">  
                            
                            <%= form.submit "New Comment", class: "btn btn-success" %>
                        </div>
                    <fieldset>
                        <div class="row">
                            <div class="col-sm-3 col-lg-2 hidden-xs">
                            	<img class="img-responsive" src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="">
                            </div>
                            <div class="form-group col-xs-12 col-sm-9 col-lg-10">
                                <%= form.text_area :text,value: @order.id, placeholder: "Your message", class: "form-control" %>
                            </div>
                        </div>  	
                    </fieldset>
                <% end %>

                <h3><%= @comments.count %> Total Comments</h3>
                
                <div id="likes"><%= render 'orders/old_comments' %></div>
                
            </div>
        </div>
    </div>
</section>

app/views/orders/_form.html.erb
      <%= form_with(model: order) do |form| %>
        <% if order.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>
      
            <ul>
              <% order.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      
      <h2 class="mb-4"><strong>Issue Order</strong></h2>
            <div class="row">
              <div class="field col-md-3">
                <%= form.label :order_number %>
                <%= form.text_field :order_number, value: @order_id, class: "form-control", :readonly => true %>
              </div>

              <div class="field col-md-3 ">
                <%= form.label :issued_by %>
                <%= form.text_field :issued_by, value: current_user.email, class: "form-control", :readonly => true %>
              </div>

              <div class="field col-md-3 ">
                <%= form.label :department %>
                <%= form.text_field :department, value: current_user.department, class: "form-control", :readonly => true %>
              </div>

              <div class="field col-md-12">
                <%= form.label :title %>
                <%= form.text_field :title, class: "form-control", :readonly => false %>
              </div>
            </div>
      
        <div class="row">
          <div class="field col-md-12">
            <%= form.label :description %>
            <%= form.text_area :description, class: "form-control", :readonly => false %>
          </div>
        </div> 
        
        <div class="form-group">  
          <%= form.submit class: 'btn btn-primary', :readonly => false  %>
        </div>
        <hr>

        <h2 h2 class="text-center mb-5"><strong>Approval</strong></h2>
  
          <div class="row mb-4">
            <div class="field col-md-3">
              <%= form.label :approved %>
              <%= form.select :approved, options_for_select(["Yes", "No"]),{:prompt => "Select One"}, {class: "form-control",:readonly => (current_user.is_admin? || current_user.position == "Fields General Manager" ? false : true)} %>
            </div>
            <div class="field col-md-3">
              <%= form.label :approved_by %>
              <%= form.text_field :approved_by, value: current_user.email,
              class: "form-control", :readonly=> (current_user.is_admin? ? false : true) %>
            </div>
          </div>
        
          <div class="row mb-4">
            <div class="field col-md-3">
              <%= form.label :recieved %>
              
                <%= form.select :recieved, options_for_select(["Yes", "No"]),{:prompt => "Select One"}, 
                                      {class: "form-control", 
                                      :readonly => (current_user.is_admin? || current_user.department == "Construction" ? false : true)} %>
              
            </div>

            <div class="field col-md-3">
              <%= form.label :recieved_by %>
              <%= form.text_field :recieved_by, class: "form-control", :readonly => true %>
            </div>

            <div class="field col-md-3">
              <%= form.label :status %>
              <%= form.select :status, options_for_select(["Pendding Approvals", "In Progress","Completed", "Canceled"]),{}, 
                                    {class: "form-control",
                                    :readonly => (current_user.is_admin? || current_user.department == "Construction" ? false : true)} %>
            </div>
        </div>
      
        <div class="row mb-4">
          <div class="field col-md-3">
            <%= form.label :closed %>
            <%= form.select :closed, options_for_select(["Yes", "No"]),{:prompt => "Select One"}, {class: "form-control", :readonly => true} %>
          </div>
          <div class="field col-md-3">
            <%= form.label :closed_by %>
            <%= form.text_field :closed_by, class: "form-control", :readonly => true %>
          </div>
        
          <div class="field col-md-3">
            <%= form.label :actions %>
            <%= form.text_field :actions, class: "form-control", :readonly => false %>
          </div>
        </div>
      
        <div class="row">
          <div class="field col-md-12 mb-5">
            <%= form.label :remarks %>
            <%= form.text_area :remarks, class: "form-control", :readonly => false %>
          </div>
        </div>
      
      
  
      
      
      <% end %>
 


   

app/views/orders/_old_comments.html.erb
<% @comments.each do |comment| %>
    <!-- COMMENT - START -->
    <div class="media">
        <a class="pull-left" href="#"><img class="media-object" src="https://bootdey.com/img/Content/avatar/avatar1.png" alt=""></a>
        <div class="media-body">
            <h4 class="media-heading"><%= user_comment_email(comment.user_id) %></h4> 
            <p><%= comment.text %></p>
            <ul class="list-unstyled list-inline media-detail pull-left">
                <li ><i class="fa fa-calendar"></i><%= comment.created_at %></li>
                <li><i class="fa fa-thumbs-up"></i><%= comment.likes.count if true %></li>
                <li><%= link_to "Edit", edit_order_comment_path(@order, comment),
                        class: 'btn btn-primary mt-2' %></li>
                <li><%= link_to "Delete", order_comment_path(@order, comment), 
                                        data: { confirm: 'Are your sure?' }, method: :delete ,
                                        class: 'btn btn-danger mt-2' %></li>
                <li>
                        <% like_dislike_method(current_user.likes, comment.likes) %>
                        <% if @my_like %>
                            <%= link_to 'Dislike', order_comment_dislike_path(@order, comment, like_id: @my_like), 
                                            method: :delete,
                                            class: 'btn btn-dark', remote: true %>

                        <% else %>
                            <%= link_to 'Like', order_comment_like_path(@order, comment), 
                                            class: 'btn btn-success mt-2', remote: true %>
                        <% end %>

                </li>
            </ul>
        </div>
    </div>      
    <!-- COMMENT - END -->
<% end %>

app/views/orders/_old_comments.js.erb
document.querySelector('#likes').innerHTML = '<%= j render 'orders/old_comments.html' %>'


app/views/orders/_search_result.html.erb
<div class="results-block">
    <%= render 'layouts/messages' %>
</div>

<% if @orders_search_res %>

        <div class="table-scroll">
          <table class="table table-bordered table-hover">
          <thead>
            <tr>
              <th class="col-2">Order Number</th>
              <th class="col-2">Title</th>
              <th class="col-4">Description</th>
              <th>Recieved</th>
              <th>Approved</th>
              <th>Closed</th>
              <th>Status</th>
              <th>Action</th>
            </tr>
          </thead>

          <tbody>
            <% @orders_search_res.each do |order| %>
              <tr>
                <td><%= order.order_number %></td>
                <td><%= order.title %></td>
                <td><%= order.description %></td>
                <td><%= order.recieved %></td>
                <td><%= order.approved %></td>
                <td><%= order.closed %></td>
                <td><%= order.status %></td> 
                <td><%= link_to 'Show', order, class: 'btn btn-primary mb-1' %>
                    <% if current_user.is_admin? || current_user.id == order.user_id || current_user.position == "Fields General Manager" %>
                      <%= link_to 'Edit', edit_order_path(order), class: 'btn btn-warning mb-1' %>
                    <% end %>
                    <%= (link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger') if current_user.is_admin? %> 
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <div>
 
<% end %>

app/views/orders/_search_result.js.erb
document.querySelector('#search_results').innerHTML = '<%= j render 'orders/search_result.html' %>'

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order, class: 'link-primary' %> |
<%= link_to 'Back', orders_path, class: 'link-primary' %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<div class='search-area'>
    <%= form_tag search_order_path, remote: true, method: :get do %>
        <div class="form-group row">
            <div class="col-sm-9  no-right-padding">
              <%= text_field_tag :order, params[:order], {placeholder: 'order_number(WO-xx-x-yyyy) , title , or description', autofocus: true, class: "form-control form-control-lg"}  %>        
            </div>
            <div class="col-sm-3 no-left-padding">
                <%= button_tag type: :submit, class: "btn btn-success" do %>
                    <%= fa_icon 'search 2x' %>
                <% end %>
            </div>
        </div>
    <% end %>
</div>
      
<div id="search_results"></div>

<h1 class="mt-5 mb-3">Work Orders</h1>
        <p>
        Download: 
        <%= link_to 'CSV', orders_path(format: "csv") , class: 'btn btn-success' %>
        </p>
        <div class="table-scroll">
          <table class="table table-bordered table-hover">
            <thead>
              <tr>
                <th class="col-2">Order Number</th>
                <th class="col-2">Title</th>
                <th class="col-4">Description</th>
                <th>Recieved</th>
                <th>Approved</th>
                <th>Closed</th>
                <th>Status</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              <% @orders.each do |order| %>
                <tr >
                  <td><%= order.order_number %></td>
                  <td><%= order.title %></td>
                  <td><%= order.description %></td>
                  <td><%= order.recieved %></td>
                  <td><%= order.approved %></td>
                  <td><%= order.closed %></td>
          
                  <td <% if order.status == 'Pendding Approvals' %>
                         class="text-warning">
                  <% elsif order.status == 'In Progress'  %>
                         class="text-success">
                  <% elsif order.status == 'Completed'  %>
                         class="text-info">
                  <% else  %>
                        class="text-danger">
                  <% end %><%= order.status %></td>
          
                    <td><%= link_to 'Show', order, class: 'btn btn-primary mb-1' %>
                      <% if current_user.is_admin? || current_user.id == order.user_id  %>
                        <%= link_to 'Edit', edit_order_path(order), class: 'btn btn-warning mb-1' %>
                      <% end %>
                      <%= (link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger') if current_user.is_admin? %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <br>
        <div class="create-order-link-margin"><%= link_to 'Create New Order', new_order_path, class: 'btn btn-success mb-5' %></div>
    

app/views/orders/my_orders.html.erb
<h1>Orders Need fields Manager Approval</h1>
<% if current_user.position == "Fields General Manager" %>   
    <% if !@pendding_orders.empty? %>
        <div class="table-scroll">
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                    <th class="col-2">Order Number</th>
                    <th class="col-2">Title</th>
                    <th class="col-4">Description</th>
                    <th>Recieved</th>
                    <th>Approved</th>
                    <th>Closed</th>
                    <th>Status</th>
                    <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                        <% @pendding_orders.each do |order| %>
            
                            <tr>
                                <td><%= order.order_number %></td>
                                <td><%= order.title %></td>
                                <td><%= order.description %></td>
                                <td><%= order.recieved %></td>
                                <td><%= order.approved %></td>
                                <td><%= order.closed %></td>
                                <td><%= order.status %></td>
                                <td><%= link_to 'Show', order, class: 'btn btn-primary mb-1' %>
                                    <% if current_user.is_admin? || current_user.id == order.user_id %>
                                    <%= link_to 'Edit', edit_order_path(order), class: 'btn btn-warning mb-1' %>
                                    <% end %>
                                    <%= (link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger') if current_user.is_admin? %>
                                </td>
                            </tr>
                        <% end %>
                </tbody>
            </table>
        </div>
    <% else %>
        <h2 class="secondary mt-5 mb-5"><span> There are no pendding records for you</span></h2>
    <% end %>
<% else %>
    <h2 class="secondary mt-5 mb-5"><span> items here for fields manager approvals</span></h2>
<% end %>
<hr>

<h1>Orders Issued by Me</h1>
<p>
Download: 
<%= link_to 'CSV', my_order_path(format: "csv") , class: 'btn btn-success' %>
</p>
<% if !current_user.orders.empty? %>
<div class="table-scroll">
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
            <th class="col-2">Order Number</th>
            <th class="col-2">Title</th>
            <th class="col-4">Description</th>
            <th>Recieved</th>
            <th>Approved</th>
            <th>Closed</th>
            <th>Status</th>
            <th>Action</th>
            </tr>
        </thead>
        <tbody>
                <% current_user.orders.each do |order| %>
    
                    <tr>
                        <td><%= order.order_number %></td>
                        <td><%= order.title %></td>
                        <td><%= order.description %></td>
                        <td><%= order.recieved %></td>
                        <td><%= order.approved %></td>
                        <td><%= order.closed %></td>
                        <td><%= order.status %></td>
                        <td><%= link_to 'Show', order, class: 'btn btn-primary mb-1' %>
                            <% if current_user.is_admin? || current_user.id == order.user_id  %>
                            <%= link_to 'Edit', edit_order_path(order), class: 'btn btn-warning mb-1' %>
                            <% end %>
                            <%= (link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger') if current_user.is_admin? %>
                        </td>
                    </tr>
                <% end %>
        </tbody>
    </table>
</div>
<% else %>
    <h2 class="secondary mt-5 mb-5"><span> You have not created any orders</span> </h2>
<% end %>

app/views/orders/new.html.erb
<div class="row">
    <div class="col mb-4 text-center">
        <h1><strong>New Order</strong></h1>
    </div>
</div>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<h1 class="mt-5 mb-3"><%= @order.order_number %></h1>
        <p>
        Download: 
        <%= link_to 'CSV', orders_path(format: "csv") , class: 'btn btn-success' %>
        </p>
        <div class="table-scroll">
          <table class="table table-bordered table-hover">
            <thead>
              <tr>
                <th class="col-2">Order Number</th>
                <th class="col-2">Title</th>
                <th class="col-4">Description</th>
                <th>Recieved</th>
                <th>Approved</th>
                <th>Closed</th>
                <th>Status</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
                <tr>
                  <td><%= @order.order_number %></td>
                  <td><%= @order.title %></td>
                  <td><%= @order.description %></td>
                  <td><%= @order.recieved %></td>
                  <td><%= @order.approved %></td>
                  <td><%= @order.closed %></td>
                  <td <% if @order.status == 'Pendding Approvals' %>
                         @class="text-warning">
                  <% elsif @order.status == 'In Progress'  %>
                         class="text-success">
                  <% elsif @order.status == 'Completed'  %>
                         class="text-info">
                  <% else  %>
                        class="text-danger">
                  <% end %>
                     <td> 
                        <% if current_user.is_admin? || current_user.id == @order.user_id  %>
                          <%= link_to 'Edit', edit_order_path(@order), class: 'btn btn-warning mb-1' %>
                        <% end %>
                        <%= (link_to 'Destroy', @order, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger') if current_user.is_admin? %>
                  </td>
                </tr>
            </tbody>
          </table>
        </div>

<%= render 'orders/comments' %>

<%= link_to 'Edit', edit_order_path(@order), class: "link-primary" %> |
<%= link_to 'Back', orders_path, class: "link-primary" %>